apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{.Values.route.name}}
  name: {{.Values.route.appname}}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: dot-net
    weight: 100
    Path: /api/employee/getemployeelist
