name: CI

 

on:
  push:
    branches:
      - main

 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

 

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.x

 

      - name: Build
        run: dotnet build

 

      - name: Test
        run: dotnet test
